source 'https://rubygems.org'

gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-contrib', require: 'sinatra/reloader'
gem 'rack'
gem 'rack-test'
gem 'minitest'
gem 'shotgun'
gem 'slim'
gem 'sinatra-assetpack', require: 'sinatra/assetpack'
gem 'compass-rails'
gem 'zurb-foundation'