source 'https://rubygems.org'

gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-contrib', require: 'sinatra/reloader'
gem 'rack'
gem 'rack-test'
gem 'minitest'
gem 'shotgun'
gem 'haml'
gem 'better_errors', require: 'better_errors'
gem 'binding_of_caller'